repos:
-   repo: git@gitlab.sol.onetick.com:solutions/pre-commit.git
    rev: v0.0.11
    hooks:
    -   id: isort
        args: ["--profile", "black"]
    -   id: black
    -   id: pylama
        args: ["--ignore", "E203", "--linters", "pycodestyle"]
        additional_dependencies: ["setuptools<82.0.0"]
    -   id: trailing-whitespace
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: end-of-file-fixer
    -   id: check-xml
